version: '3.9'

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      -6379:6379
    command: ["redis-server","--appendonly","yes"]
    # redis-server : start the redis server
    # --appendonly yes ==> enables AOF (append only File) persistance
    # AOF logs every write operation and replays them when redis restart
    # this ensures better durability since it logs every change to the disk
    